# Generated by Django 3.0.7 on 2020-12-09 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ManyToManyField(related_name='linkingUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
