# Generated by Django 3.0.7 on 2020-12-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_auto_20201209_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
